# SPDX-FileCopyrightText: © 2025 Stefan Siegel <ssiegel@sdas.net>
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
    "deno.lock",
    "src/lib/types/grocy.d.ts"
]
SPDX-FileCopyrightText = "© 2025 Stefan Siegel <ssiegel@sdas.net>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "README.md",
    "static/favicon.*"
]
SPDX-FileCopyrightText = "© 2025 Stefan Siegel <ssiegel@sdas.net>"
SPDX-License-Identifier = "CC-BY-SA-4.0 OR AGPL-3.0-or-later"

[[annotations]]
path = "src/assets/fonts/TanoheSans-*"
SPDX-FileCopyrightText = [
    "© 2014, Cooper Hewitt Smithsonian Design Museum (cooperhewitt.org), with Reserved Font Name COOPER HEWITT",
    "© 2019-2020 by Cristiano Sobral (cssobral2013@gmail.com)"
]
SPDX-License-Identifier = "OFL-1.1"
